In [27]:
import pandas as pd
import numpy as np

In [28]:
path = "C:\\Users\\Maclan\\OneDrive\\Desktop\\Assignment 2\\king_rook_vs_king.csv"
data = pd.read_csv(path)
df = pd.DataFrame(data)
df.head()

white_king_file  white_king_rank white_rook_file  white_rook_rank  \
0               a                1               b                3   
1               a                1               c                1   
2               a                1               c                1   
3               a                1               c                1   
4               a                1               c                2   

  black_king_file  black_king_rank white_depth_of_win  
0               c                2               draw  
1               c                2               draw  
2               d                1               draw  
3               d                2               draw  
4               c                1               draw

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28056 entries, 0 to 28055
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   white_king_file     28056 non-null  object
 1   white_king_rank     28056 non-null  int64 
 2   white_rook_file     28056 non-null  object
 3   white_rook_rank     28056 non-null  int64 
 4   black_king_file     28056 non-null  object
 5   black_king_rank     28056 non-null  int64 
 6   white_depth_of_win  28056 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.5+ MB


In [30]:
df.isnull().sum()

white_king_file       0
white_king_rank       0
white_rook_file       0
white_rook_rank       0
black_king_file       0
black_king_rank       0
white_depth_of_win    0
dtype: int64

In [31]:
df["white_king_file"].value_counts()

white_king_file
d    12136
c     8726
b     5316
a     1878
Name: count, dtype: int64

In [32]:
for col in df.columns:
    print(df[col].value_counts())

white_king_file
d    12136
c     8726
b     5316
a     1878
Name: count, dtype: int64
white_king_rank
1    12666
2     8540
3     5130
4     1720
Name: count, dtype: int64
white_rook_file
h    3616
g    3599
f    3582
e    3576
a    3468
b    3438
c    3409
d    3368
Name: count, dtype: int64
white_rook_rank
5    3549
4    3541
6    3531
7    3514
3    3512
8    3497
2    3483
1    3429
Name: count, dtype: int64
black_king_file
h    4848
g    4600
f    4352
e    3450
a    2920
d    2796
b    2700
c    2390
Name: count, dtype: int64
black_king_rank
5    3822
4    3788
1    3664
6    3608
3    3506
7    3360
2    3196
8    3112
Name: count, dtype: int64
white_depth_of_win
fourteen    4553
thirteen    4194
twelve      3597
eleven      2854
draw        2796
fifteen     2166
ten         1985
nine        1712
eight       1433
seven        683
six          592
five         471
sixteen      390
two          246
four         198
three         81
one           78
zero          27
Name: count, dt

In [33]:
df_encoded = pd.get_dummies(df, columns=['white_king_file', 'white_rook_file','black_king_file'], drop_first=True)

In [34]:
df_encoded.head()

white_king_rank  white_rook_rank  black_king_rank white_depth_of_win  \
0                1                3                2               draw   
1                1                1                2               draw   
2                1                1                1               draw   
3                1                1                2               draw   
4                1                2                1               draw   

   white_king_file_b  white_king_file_c  white_king_file_d  white_rook_file_b  \
0              False              False              False               True   
1              False              False              False              False   
2              False              False              False              False   
3              False              False              False              False   
4              False              False              False              False   

   white_rook_file_c  white_rook_file_d  ...  white_rook_file_f  \
0              False              False  ...              False   
1               True              False  ...              False   
2               True              False  ...              False   
3               True              False  ...              False   
4               True              False  ...              False   

   white_rook_file_g  white_rook_file_h  black_king_file_b  black_king_file_c  \
0              False              False              False               True   
1              False              False              False               True   
2              False              False              False              False   
3              False              False              False              False   
4              False              False              False               True   

   black_king_file_d  black_king_file_e  black_king_file_f  black_king_file_g  \
0              False              False              False              False   
1              False              False              False              False   
2               True              False              False              False   
3               True              False              False              False   
4              False              False              False              False   

   black_king_file_h  
0              False  
1              False  
2              False  
3              False  
4              False  

[5 rows x 21 columns]

In [35]:
depth_mapping = {
    'draw': 0,
    'zero': 1, 'one': 1, 'two': 1, 'three': 1, 'four': 1,
    'five': 2, 'six': 2, 'seven': 2, 'eight': 2,
    'nine': 3, 'ten': 3, 'eleven': 3, 'twelve': 3,
    'thirteen': 4, 'fourteen': 4, 'fifteen': 4, 'sixteen': 4
}

# Apply the transformation
df_encoded['win_depth_level'] = df_encoded['white_depth_of_win'].map(depth_mapping)

# Display the transformed DataFrame
df_encoded

white_king_rank  white_rook_rank  black_king_rank white_depth_of_win  \
0                    1                3                2               draw   
1                    1                1                2               draw   
2                    1                1                1               draw   
3                    1                1                2               draw   
4                    1                2                1               draw   
...                ...              ...              ...                ...   
28051                1                7                5            sixteen   
28052                1                7                6            sixteen   
28053                1                7                7            sixteen   
28054                1                7                5            sixteen   
28055                1                7                5            sixteen   

       white_king_file_b  white_king_file_c  white_king_file_d  \
0                  False              False              False   
1                  False              False              False   
2                  False              False              False   
3                  False              False              False   
4                  False              False              False   
...                  ...                ...                ...   
28051               True              False              False   
28052               True              False              False   
28053               True              False              False   
28054               True              False              False   
28055               True              False              False   

       white_rook_file_b  white_rook_file_c  white_rook_file_d  ...  \
0                   True              False              False  ...   
1                  False               True              False  ...   
2                  False               True              False  ...   
3                  False               True              False  ...   
4                  False               True              False  ...   
...                  ...                ...                ...  ...   
28051              False              False              False  ...   
28052              False              False              False  ...   
28053              False              False              False  ...   
28054              False              False              False  ...   
28055              False              False              False  ...   

       white_rook_file_g  white_rook_file_h  black_king_file_b  \
0                  False              False              False   
1                  False              False              False   
2                  False              False              False   
3                  False              False              False   
4                  False              False              False   
...                  ...                ...                ...   
28051               True              False              False   
28052               True              False              False   
28053               True              False              False   
28054               True              False              False   
28055               True              False              False   

       black_king_file_c  black_king_file_d  black_king_file_e  \
0                   True              False              False   
1                   True              False              False   
2                  False               True              False   
3                  False               True              False   
4                   True              False              False   
...                  ...                ...                ...   
28051              False              False               True   
28052              False              False               True   
28053              False 

In [36]:
df_encoded = df_encoded.drop(columns=['white_depth_of_win'])
df_encoded.shape

(28056, 21)

In [44]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [45]:
# Splitting data into features (X) and target (y)
X = df_encoded.drop(columns=['win_depth_level'])
y = df_encoded['win_depth_level']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
rf_classifier = RandomForestClassifier(random_state=42)

In [48]:
param_grid = {
    'n_estimators': [50, 100, 200],            # Number of trees in the forest
    'max_depth': [5, 10, 15, None],             # Maximum depth of each tree
    'min_samples_split': [2, 5, 10],            # Minimum samples required to split a node
    'min_samples_leaf': [1, 2, 4],              # Minimum samples required at a leaf node
    'max_features': ['auto', 'sqrt', 'log2'],   # Number of features to consider for the best split
    'bootstrap': [True, False]                  # Whether bootstrap samples are used when building trees
}

In [49]:
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')

In [50]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 648 candidates, totalling 3240 fits


C:\Users\Maclan\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
1080 fits failed out of a total of 3240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
529 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Maclan\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Maclan\anaconda3\lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Users\Maclan\anaconda3\lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Maclan\anaconda3\lib\site

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'max_depth': [5, 10, 15, None],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy', verbose=2)

In [51]:
best_params = grid_search.best_params_

print(f"Best Hyperparameters: {best_params}")

best_rf_classifier = grid_search.best_estimator_

Best Hyperparameters: {'bootstrap': True, 'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}


In [52]:
cv_scores = cross_val_score(best_rf_classifier, X_train, y_train, cv=5)

In [53]:
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean cross-validation score: {cv_scores.mean()}")

Cross-validation scores: [0.8451771  0.840499   0.8398307  0.83604366 0.83845811]
Mean cross-validation score: 0.8400017134377598


In [58]:
best_rf_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [59]:
y_pred = best_rf_classifier.predict(X_test)
y_train_pred = best_rf_classifier.predict(X_train)

In [60]:
train_accuracy = accuracy_score(y_train,y_train_pred)
test_accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
classfication_report = classification_report(y_test, y_pred)

In [61]:
print("Train Accuracy:\n", train_accuracy)
print("Test Accuracy:\n", test_accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classfication_report)

Train Accuracy:
 1.0
Test Accuracy:
 0.8601211689237348
Confusion Matrix:
 [[ 314    4   24   74  133]
 [   2   99   24    5    0]
 [  12    3  541   68   12]
 [  30    1   34 1846  161]
 [  61    0    2  135 2027]]
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.57      0.65       549
           1       0.93      0.76      0.84       130
           2       0.87      0.85      0.86       636
           3       0.87      0.89      0.88      2072
           4       0.87      0.91      0.89      2225

    accuracy                           0.86      5612
   macro avg       0.86      0.80      0.82      5612
weighted avg       0.86      0.86      0.86      5612

