In [3]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [4]:
path = "C:\\Users\\LENOVO\\Desktop\\KDDM 2\\king_rook_vs_king.csv"
data = pd.read_csv(path)
df = pd.DataFrame(data)
df.head()

white_king_file  white_king_rank white_rook_file  white_rook_rank  \
0               a                1               b                3   
1               a                1               c                1   
2               a                1               c                1   
3               a                1               c                1   
4               a                1               c                2   

  black_king_file  black_king_rank white_depth_of_win  
0               c                2               draw  
1               c                2               draw  
2               d                1               draw  
3               d                2               draw  
4               c                1               draw

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28056 entries, 0 to 28055
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   white_king_file     28056 non-null  object
 1   white_king_rank     28056 non-null  int64 
 2   white_rook_file     28056 non-null  object
 3   white_rook_rank     28056 non-null  int64 
 4   black_king_file     28056 non-null  object
 5   black_king_rank     28056 non-null  int64 
 6   white_depth_of_win  28056 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.5+ MB


In [6]:
df.isnull().sum()

white_king_file       0
white_king_rank       0
white_rook_file       0
white_rook_rank       0
black_king_file       0
black_king_rank       0
white_depth_of_win    0
dtype: int64

## Preprocessing

In [8]:
df_encoded = pd.get_dummies(df, columns=['white_king_file', 'white_rook_file','black_king_file'], drop_first=True)

In [9]:
df_encoded.head()

white_king_rank  white_rook_rank  black_king_rank white_depth_of_win  \
0                1                3                2               draw   
1                1                1                2               draw   
2                1                1                1               draw   
3                1                1                2               draw   
4                1                2                1               draw   

   white_king_file_b  white_king_file_c  white_king_file_d  white_rook_file_b  \
0              False              False              False               True   
1              False              False              False              False   
2              False              False              False              False   
3              False              False              False              False   
4              False              False              False              False   

   white_rook_file_c  white_rook_file_d  ...  white_rook_file_f  \
0              False              False  ...              False   
1               True              False  ...              False   
2               True              False  ...              False   
3               True              False  ...              False   
4               True              False  ...              False   

   white_rook_file_g  white_rook_file_h  black_king_file_b  black_king_file_c  \
0              False              False              False               True   
1              False              False              False               True   
2              False              False              False              False   
3              False              False              False              False   
4              False              False              False               True   

   black_king_file_d  black_king_file_e  black_king_file_f  black_king_file_g  \
0              False              False              False              False   
1              False              False              False              False   
2               True              False              False              False   
3               True              False              False              False   
4              False              False              False              False   

   black_king_file_h  
0              False  
1              False  
2              False  
3              False  
4              False  

[5 rows x 21 columns]

In [10]:
depth_mapping = {
    'draw': 0,
    'zero': 1, 'one': 1, 'two': 1, 'three': 1, 'four': 1,
    'five': 2, 'six': 2, 'seven': 2, 'eight': 2,
    'nine': 3, 'ten': 3, 'eleven': 3, 'twelve': 3,
    'thirteen': 4, 'fourteen': 4, 'fifteen': 4, 'sixteen': 4
}

# Apply the transformation
df_encoded['win_depth_level'] = df_encoded['white_depth_of_win'].map(depth_mapping)

# Display the transformed DataFrame
df_encoded.head()

white_king_rank  white_rook_rank  black_king_rank white_depth_of_win  \
0                    1                3                2               draw   
1                    1                1                2               draw   
2                    1                1                1               draw   
3                    1                1                2               draw   
4                    1                2                1               draw   
...                ...              ...              ...                ...   
28051                1                7                5            sixteen   
28052                1                7                6            sixteen   
28053                1                7                7            sixteen   
28054                1                7                5            sixteen   
28055                1                7                5            sixteen   

       white_king_file_b  white_king_file_c  white_king_file_d  \
0                  False              False              False   
1                  False              False              False   
2                  False              False              False   
3                  False              False              False   
4                  False              False              False   
...                  ...                ...                ...   
28051               True              False              False   
28052               True              False              False   
28053               True              False              False   
28054               True              False              False   
28055               True              False              False   

       white_rook_file_b  white_rook_file_c  white_rook_file_d  ...  \
0                   True              False              False  ...   
1                  False               True              False  ...   
2                  False               True              False  ...   
3                  False               True              False  ...   
4                  False               True              False  ...   
...                  ...                ...                ...  ...   
28051              False              False              False  ...   
28052              False              False              False  ...   
28053              False              False              False  ...   
28054              False              False              False  ...   
28055              False              False              False  ...   

       white_rook_file_g  white_rook_file_h  black_king_file_b  \
0                  False              False              False   
1                  False              False              False   
2                  False              False              False   
3                  False              False              False   
4                  False              False              False   
...                  ...                ...                ...   
28051               True              False              False   
28052               True              False              False   
28053               True              False              False   
28054               True              False              False   
28055               True              False              False   

       black_king_file_c  black_king_file_d  black_king_file_e  \
0                   True              False              False   
1                   True              False              False   
2                  False               True              False   
3                  False               True              False   
4                   True              False              False   
...                  ...                ...                ...   
28051              False              False               True   
28052              False              False               True   
28053              False 

In [11]:
df_encoded = df_encoded.drop(columns=['white_depth_of_win'])
df_encoded.shape

(28056, 21)

In [23]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [13]:
# Splitting data into features (X) and target (y)
X = df_encoded.drop(columns=['win_depth_level'])
y = df_encoded['win_depth_level']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Standard Scaler

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
model = DecisionTreeClassifier(random_state=42)

In [26]:
param_grid = {
    'criterion': ['gini', 'entropy'],            # Measure for splitting nodes
    'max_depth': [None, 10, 20, 30],              # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],              # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4],                # Minimum number of samples required at a leaf node
    'max_features': [None, 'sqrt', 'log2'],      # Number of features to consider for the best split
    'splitter': ['best', 'random'],              # Strategy used to split at each node
    'max_leaf_nodes': [None, 10, 20, 30]        # Maximum number of leaf nodes in the tree
}  

In [27]:
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')

In [28]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 1728 candidates, totalling 8640 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10, 20, 30],
                         'max_features': [None, 'sqrt', 'log2'],
                         'max_leaf_nodes': [None, 10, 20, 30],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'splitter': ['best', 'random']},
             scoring='accuracy', verbose=2)

In [29]:
best_params = grid_search.best_params_

print(f"Best Hyperparameters: {best_params}")

best_classifier = grid_search.best_estimator_

Best Hyperparameters: {'criterion': 'gini', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}


In [30]:
cv_scores = cross_val_score(best_classifier, X_train, y_train, cv=5)

In [31]:
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean cross-validation score: {cv_scores.mean()}")

Cross-validation scores: [0.86901314 0.8498552  0.86121631 0.86388951 0.86720143]
Mean cross-validation score: 0.8622351170160849


In [32]:
best_classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [33]:
y_pred = best_classifier.predict(X_test)
y_train_pred = best_classifier.predict(X_train)

In [34]:
train_accuracy = accuracy_score(y_train,y_train_pred)
test_accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
classfication_report = classification_report(y_test, y_pred)

In [35]:
print("Train Accuracy:\n", train_accuracy)
print("Test Accuracy:\n", test_accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classfication_report)

Train Accuracy:
 1.0
Test Accuracy:
 0.8970064148253742
Confusion Matrix:
 [[ 408    6   50   50   35]
 [  14   99   15    2    0]
 [  35    9  540   50    2]
 [  46    3   48 1894   81]
 [  53    0    5   74 2093]]
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.74      0.74       549
           1       0.85      0.76      0.80       130
           2       0.82      0.85      0.83       636
           3       0.91      0.91      0.91      2072
           4       0.95      0.94      0.94      2225

    accuracy                           0.90      5612
   macro avg       0.85      0.84      0.85      5612
weighted avg       0.90      0.90      0.90      5612

